services:
  - type: web
    name: blog-backend
    env: python
    buildCommand: |
      echo "python-3.10.13" > runtime.txt
      pip install -r requirements.txt
    startCommand: gunicorn blog_backend.wsgi:application
